### ISSUE TITLE
wm.exe hangs sometimes after re-dock

### ISSUE THREAD

**Issue by zoidy** [manutalcual/winredock#14] opened 2019-01-04 18:06 UTC
Sometimes the program hangs after re-docking. I can't reliably replicate but it seems to happen most often when the screen gets locked while undocked and I re-dock while the screen is locked. After logging in, the wm.exe process hangs with 100% CPU usage and no windows get repositioned.

I was able to capture an occurrence using the logging version from [this ](https://github.com/manutalcual/winredock/commit/56a7f33db85db3a54cc5883c4dcfb14e3e362a24)commit
[wm.log](https://github.com/manutalcual/winredock/files/2728011/wm.log)

**Comment by raidersan** [comment] 2019-12-04 14:10
Same issue here, dont know what triggers it, don't think it is the lock screen process per se, could be linked to the dock/undocked status change while locked/sleeping

**Comment by manutalcual** [comment] 2019-12-10 10:01
I think it is the loop that verifies the windows when there is a lock between two resolutions. When the laptop is in lock or suspended, it doesn't gets resolution updates. When this occur, there is a little function to check windows existence, screen resolution and positions and tries to do things.
Obviously this isn't working well and I'm not sure if it takes a long time or is an infinite loop.
The workaround is to undock/dock always with the laptop awake and/or not locked.

Sorry guys not to have time to fix this. I have currently two jobs only to pay the bills, so I don't have time to fix/work on this.

Thank you for your time to use this and to report things. I will eventually work on this when I have time.

**Comment by sbiefeni** [comment] 2020-02-19 19:31
Any chance for a resolution for this?

**Comment by sbiefeni** [comment] 2020-02-19 19:48
It seems to be that first run, it's fine. 
1. run - ok
2. undock - ok
3. dock - ok - windows reposition, perfect.
4. undock - now vm.exe is frozen, and CPU usage starts to rise.
5. dock - fail to position windows.

the CPU usage rises gradually too, it's doesn't start at 100%.. it rises.. 10%...20%... etc.. so it's like it's building up cycles.

**Comment by manutalcual** [comment] 2020-02-20 08:25
I will test it this weekend.

**Comment by sbiefeni** [comment] 2020-02-20 19:08
That would be awesome.. thanks Manuel.

Another issue - 
I have multiple desktops - 5
I notice that often, it correctly moves windows to the external monitor when docking, but not to the original desktop they were on. It sometimes works, but sometimes it piles all the windows onto the leftmost desktop.

**Comment by manutalcual** [comment] 2020-02-21 13:47
Ok. I'll try to debug this evening and weekend.

**Comment by manutalcual** [comment] 2020-02-24 09:31
I've tested this over the weekend and I think I've found a bug and solved but didn't have time to put a release. I'll do it this evening (my time is UTC+2 by the way.)

**Comment by ziddey** [comment] 2020-03-02 20:36
seeing the same behavior as @sbiefeni. However, it seems to not be related to screen lock for me. Just an unplug/replug will do. Subsequent unplug/replug will not restore, and a core is pegged.

**Comment by manutalcual** [comment] 2020-03-03 09:21
I have that pending. Unfortunately I didn't have time to upload the code and make a release :-(. Will try to do it today.

**Comment by sbiefeni** [comment] 2020-03-04 00:07
> seeing the same behavior as @sbiefeni. However, it seems to not be related to screen lock for me. Just an unplug/replug will do. Subsequent unplug/replug will not restore, and a core is pegged.

I think you're referring to the same issue I was talking about... dock = plug, undock  = unplug.

**Comment by ziddey** [comment] 2020-03-04 00:43
@sbiefeni right, @zoidy was saying something about screen locking in the original post

**Comment by manutalcual** [comment] 2020-03-04 08:18
I'm sorry guys, I didn't do it yet. I've been working twelve hours a day and don't had time. Will try today.

**Comment by Mystravil** [comment] 2020-03-04 09:01
@manutalcual please don't stress yourself with this. Focus on important things first

**Comment by manutalcual** [comment] 2020-03-04 20:04
I've made a release based on the bug fix. I'm not sure it is solved because I can't reproduce the failure, but you may try.
Release: v0.2bf

**Comment by starryalley** [comment] 2020-03-05 05:04
The exe depends on libstdc++-6.dll/libgcc_s_seh-1.dll which aren't included in the zip. 

I tried to build your branch "ISSUE_0014" myself and the wm.exe doesn't actually depend on those 2, but the ones who cyg*.

**Comment by manutalcual** [comment] 2020-03-05 08:02
@starryalley can you confirm if it doesn't hung when plugin and unplugin?

**Comment by manutalcual** [comment] 2020-03-05 20:23
I've made another release that should work better.
[This](https://github.com/manutalcual/winredock/tree/v0.3bf) has support for multi-window applications (i.e. apps that have more than one window but are equal, like Firefox, Chrome, not apps that have several different windows (like apps with tool windows.)

**Comment by sbiefeni** [comment] 2020-03-05 20:40
I'm not able to run wm.exe because of this error.. I'm not compiling the program, just running the file from bin.

![Annotation 2020-03-05 123824](https://user-images.githubusercontent.com/4406427/76023671-6e082680-5ede-11ea-82df-0f8a2df87f62.png)

**Comment by manutalcual** [comment] 2020-03-06 08:28
I've created another issue for the missing dlls. #24 
I'm merging and closing this issue.

**Closed by manutalcual** 2020-03-06 08:28 UTC
