### ISSUE TITLE
Monitors with different DPI settings thrown Winredock off

### ISSUE THREAD

**Issue by raidersan** [manutalcual/winredock#36] opened 2020-11-03 13:37 UTC
First of all, thank you for building this app and making it available.
I have a laptop with a super resolution and therefore I set the dpi setting much higher in Win10 so that I have a chance to read the content of it. I have a "normal" external monitor that I leave at 100dpi as per default.
When I connect my external screen, Winredock kicks in and places the window their original location, but the sizes are always wrong, always too small, Is Winredock storing sizes that are not DPI-aware?

**Comment by manutalcual** [comment] 2020-11-03 13:49
Hi,

Thanks for using it and taking time to note this.
Yes, it is a known problem. Default DPI is 96 not 100. But that's doesn't matter for this.
I'm struggling to fix that. I didn't have a Windows machine for a long time, but now I can develop and test in a virtual machine.
The problem is basically that not every app is DPI aware (Winredock isn't in the last release) but I'm working on it.
I'll give news in #21 and close this as repeated.

Thanks!

Duplicate of #21.

**Closed by manutalcual** 2020-11-03 13:49 UTC
